config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cards, only: [:index] do
    member do
      put 'want'
      put 'have'
    end
    collection do
      post 'album'
    end
  end

  resources :users, only: %i[index show], path: 'u' do
    member do
      get 'wants'
      get 'haves'
    end
  end

  root to: 'cards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  include PgSearch

  CARD_PROPS = %i[name colors color_identity type rarity text power toughness mana_cost names].freeze
  PRINTING_PROPS = %i[set image_url multiverse_id id].freeze

  pg_search_scope :search_by_name, against: %i[name portuguese_name], ignoring: :accents,
                                   using: { tsearch: { prefix: true, negation: true } },
                                   ranked_by: 'name'

  def formatted_name
    return name if portuguese_name.blank?
    "#{name} / #{portuguese_name}"
  end

  def image_url
    first_print = printings.select { |printing| printing && printing['image_url'].present? }.first
    return first_print['image_url'] if first_print.present?
  end

  def portuguese_image_url(set = nil)
    prints = portuguese_printings
    prints = portuguese_printings.select { |printing| printing.set == set } if set.present?
    return image_url(set) if prints.empty?
    image_url_for_mid prints.first['portuguese_mid']
  end

  def image_url_for_mid(mid)
    "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=#{mid}&type=card"
  end

  def portuguese_printings
    printings.select { |printing| printing['portuguese_mid'].present? }
  end

  def self.create_or_update_from(mtg_card)
    new_card = find_or_initialize_by(name: mtg_card.name)
    new_card.update_props_from(mtg_card)
    new_card.update_printings_from(mtg_card)
    new_card.save!
  end

  def update_props_from(mtg_card)
    portuguese_details = mtg_card.foreign_names&.select { |fn| fn.language == 'Portuguese (Brazil)' }&.first
    props = CARD_PROPS.map { |prop| [prop, mtg_card.send(prop)] }.to_h
    props = props.merge(portuguese_name: portuguese_details.name) if portuguese_details.present?
    update(props)
  end

  def update_printings_from(mtg_card)
    portuguese_details = mtg_card.foreign_names&.select { |fn| fn.language == 'Portuguese (Brazil)' }&.first
    new_printing = PRINTING_PROPS.map { |prop| [prop, mtg_card.send(prop)] }.to_h
    new_printing = new_printing.merge(portuguese_mid: portuguese_details.multiverse_id) if portuguese_details.present?
    add_printing(new_printing)
  end

  def add_printing(printing)
    self.printings |= []
    self.printings.delete_if { |p| p['id'] == printing[:id] }
    self.printings << printing
  end

  def self.inheritance_column
    :inheritance_type
  end
end

app/models/have_list.rb
class HaveList < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user, :card, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = %w[admin free].freeze

  devise :database_authenticatable, :rememberable, :validatable, :registerable, :confirmable, :recoverable

  enum role: ROLES.zip(ROLES).to_h

  validates :username, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :username, format: { with: /[a-zA-Z0-9_\.]*/ }

  has_many :want_list, dependent: :destroy
  has_many :have_list, dependent: :destroy

  has_many :wanted_cards, through: :want_list, source: :card
  has_many :owned_cards, through: :have_list, source: :card

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login.present?
      where(conditions.to_h).find_by(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }])
    elsif conditions.key?(:username) || conditions.key?(:email)
      find_by(conditions.to_h)
    end
  end
end

app/models/want_list.rb
class WantList < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user, :card, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[login username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!, except: %i[index album]
  before_action :extract_params
  before_action :find_cards, only: %i[index album]
  before_action :find_single_card, only: %i[want have]

  def index; end

  def album
    render 'shared/album_update'
  end

  def want
    if current_user.wanted_cards.include?(@card)
      current_user.want_list.where(card: @card).destroy_all
    else
      current_user.wanted_cards << @card
    end
    render 'shared/card_update'
  end

  def have
    if current_user.owned_cards.include?(@card)
      current_user.have_list.where(card: @card).destroy_all
    else
      current_user.owned_cards << @card
    end
    render 'shared/card_update'
  end

  private

  def extract_params
    @updatable_album = params[:updatable_album]
    @search = params[:search]
  end

  def find_cards
    @cards = Card.search_by_name(@search).limit(30)
  end

  def find_single_card
    @card = Card.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :extract_params

  def index
    @users = User.all
  end

  def show; end

  def wants
    @list_type = 'want'
    find_cards
  end

  def haves
    @list_type = 'have'
    find_cards
  end

  private

  def extract_params
    @updatable_list = params[:updatable_list]
    @updatable_album = params[:updatable_album]
    @search = params[:search]
    @user = User.find_by(username: params[:id])
  end

  def find_cards
    @cards = @list_type == 'have' ? @user.owned_cards : @user.wanted_cards
    @cards = @cards.search_by_name(@search) if @search.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
  def card_types_icon(card)
    types = card.type.split(' ').map(&:downcase) & %w[land creature instant sorcery planeswalker enchantment artifact]
    types.map { |type| "ms ms-fw ms-#{type}" }
  end

  def card_costs_icon(card)
    return [] if card.mana_cost.blank?
    card.mana_cost.scan(/\{([^\{\}]+)\}/).map do |cost|
      cost = cost.first.downcase
      cost.sub!('/', '')
      if cost.length == 2 && !cost.include?('p')
        "ms ms-fw ms-cost ms-shadow ms-split ms-#{cost.downcase}"
      else
        "ms ms-fw ms-cost ms-2x ms-shadow ms-#{cost.downcase}"
      end
    end
  end
end

app/views/cards/index.html.haml
= render partial: 'shared/card_page', locals: { user: nil, title: 'Busca', label: 'Buscar', cards: @cards, search: true }

app/views/cards/list.js.haml
$("#{@updatable}").html("#{j render 'card_list', cards: @cards, content_type: 'text/html'}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1.0", name: "viewport"}/
    %meta{content: "/", name: "turbolinks-root"}/
    %meta{name: "turbolinks-cache-control", content: "no-preview"}/
    %title ManaVai
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar-fixed
      %nav
        .nav-wrapper
          %a.brand-logo{ href: cards_path } &nbsp;ManaVai
          %a.left.sidenav-trigger.hide-on-large-only{ href: "#", "data-target" => "left-sidenav" }
            %i.material-icons menu
          %ul.right.hide-on-med-and-down
            = render partial: 'shared/menu_items'
    = render partial: 'shared/sidenav'
    .container
      %p.notice= notice
      %p.alert= alert
      = yield

app/views/shared/_card.html.haml
.card
  .card-image.activator
    = image_tag (card.image_url || 'card_back.jpg'), class: 'activator'
    %a.btn-floating.halfway-fab.card-reveal-fab.waves-effect.waves-light.z-depth-5.pink.darken-3
      %i.material-icons expand_less
  .card-reveal{ id: "card-reveal-#{card.id}" }
    = render partial: 'shared/card_reveal', locals: { card: card }

app/views/shared/_card_album.html.haml
- if cards.empty?
  .row
    .col.s12
      .center-align
        %h4.text-center Sem resultados
- else
  - cards.each_slice(3) do |three_cards|
    .row
      -three_cards.each do |card|
        .col.s12.m4{ id: "card-#{card.id}" }
          = render partial: 'shared/card', locals: { card: card }

app/views/shared/_card_page.html.haml
.row
  %h4
    %span.card-page-title
      = title
      - if user.present?
        de
        = link_to(user.username, user_path(user.username))
- if search
  .row
    = render partial: 'shared/card_search', locals: { label: label, username: user&.username }
#card_album
  = render partial: 'shared/card_album', locals: { cards: cards }

app/views/shared/_card_reveal.html.haml
.card-title.grey-text.text-darken-4
  %i.material-icons.right close
.card-content
  %p
    %b> Nome:
     #{card.name}
  %p
    %b> Tradução:
     #{card.portuguese_name}
- if current_user.present?
  .card-action
    - want_label = 'Quero!'
    - have_label = 'Tenho!'
    - want_class = 'green-text'
    - have_class = ''
    - if current_user.wanted_cards.include?(card)
      - want_label = 'Não quero mais!'
      - want_class = 'red-text'
    - if current_user.owned_cards.include?(card)
      - have_label = 'Não tenho mais!'
      - have_class = 'red-text'
    %p
      = link_to want_label, want_card_path(card), method: :put, remote: true, class: want_class
    %p
      = link_to have_label, have_card_path(card), method: :put, remote: true, class: have_class

app/views/shared/_card_search.html.haml
%nav.white
  .nav-wrapper
    = form_tag({ action: :album }, remote: true) do
      .input-field{ style: 'flex-grow: 100' }
        = search_field_tag :search, @search
        %label.label-icon{:for => "search"}
          %i.material-icons.black-text search
        = hidden_field_tag :updatable_album, '#card_album'
        = hidden_field_tag :id, username if username.present?

app/views/shared/_menu_items.html.haml
%li
  = link_to('Busca', cards_path)
- if user_signed_in?
  %li
    = link_to('Quero', wants_user_path(current_user.username))
  %li
    = link_to('Tenho', haves_user_path(current_user.username))
  %li
    = link_to('Usuários', users_path)
  %li
    = link_to('Logout', destroy_user_session_path, method: :delete, class: 'waves-effect waves-light btn')
- else
  %li
    = link_to('Login', new_user_session_path, class: 'waves-effect waves-light btn')

app/views/shared/_sidenav.html.haml
%ul.sidenav#left-sidenav
  = render partial: 'shared/menu_items'

app/views/shared/album_update.js.haml
$("#{@updatable_album}").html("#{j render 'shared/card_album', cards: @cards, content_type: 'text/html'}");

app/views/shared/card_update.js.haml
$("#card-reveal-#{@card.id}").html("#{j render 'shared/card_reveal', card: @card, content_type: 'text/html'}");

app/views/users/haves.html.haml
= render partial: 'shared/card_page', locals: { user: @user, title: 'Tenho', search: false, cards: @cards }

app/views/users/index.html.haml
.row
  %h4
    = 'Usuários'
.row
  %table.striped.highlight
    %thead
      %tr
        %th Usuário
        %th
          = user_signed_in? ? 'Quer (# tenho)' : 'Quer'
        %th
          = user_signed_in? ? 'Tem (# quero)' : 'Tem'
    %tbody
    - @users.each do |user|
      %tr
        %td
          = link_to(user.username, user_path(user.username))
        %td
          = "#{user.wanted_cards.count} (#{(user.wanted_cards.ids & current_user.owned_cards.ids).count})"
        %td
          = "#{user.owned_cards.count} (#{(user.owned_cards.ids & current_user.wanted_cards.ids).count})"

app/views/users/show.html.haml
.row
  %h4
    = @user.username
%h4
  = link_to('Quer', haves_user_path(@user.username))
%h4
  = link_to('Tem', wants_user_path(@user.username))    

app/views/users/wants.html.haml
= render partial: 'shared/card_page', locals: { user: @user, title: 'Quero', search: false, cards: @cards }